import { Recipe } from '../types';

export const recipes: Recipe[] = [
  // Tier 1 - Basic Combinations
  { ingredients: ['Earth', 'Water'], result: { id: 'mud', name: 'Mud', emoji: '💩', tier: 1 } },
  { ingredients: ['Earth', 'Fire'], result: { id: 'lava', name: 'Lava', emoji: '🌋', tier: 1 } },
  { ingredients: ['Air', 'Fire'], result: { id: 'smoke', name: 'Smoke', emoji: '💨', tier: 1 } },
  { ingredients: ['Air', 'Water'], result: { id: 'mist', name: 'Mist', emoji: '🌫️', tier: 1 } },
  { ingredients: ['Earth', 'Air'], result: { id: 'dust', name: 'Dust', emoji: '🧹', tier: 1 } },
  { ingredients: ['Fire', 'Water'], result: { id: 'steam', name: 'Steam', emoji: '♨️', tier: 1 } },
  { ingredients: ['Water', 'Water'], result: { id: 'lake', name: 'Lake', emoji: '🌊', tier: 1 } },
  { ingredients: ['Fire', 'Fire'], result: { id: 'sun', name: 'Sun', emoji: '☀️', tier: 1 } },
  { ingredients: ['Earth', 'Earth'], result: { id: 'mountain', name: 'Mountain', emoji: '⛰️', tier: 1 } },
  { ingredients: ['Air', 'Air'], result: { id: 'wind', name: 'Wind', emoji: '🌬️', tier: 1 } },

  // Tier 2 - Secondary Combinations
  { ingredients: ['Mud', 'Fire'], result: { id: 'brick', name: 'Brick', emoji: '🧱', tier: 2 } },
  { ingredients: ['Mist', 'Dust'], result: { id: 'cloud', name: 'Cloud', emoji: '☁️', tier: 2 } },
  { ingredients: ['Cloud', 'Water'], result: { id: 'rain', name: 'Rain', emoji: '🌧️', tier: 2 } },
  { ingredients: ['Rain', 'Sun'], result: { id: 'rainbow', name: 'Rainbow', emoji: '🌈', tier: 2 } },
  { ingredients: ['Mountain', 'Fire'], result: { id: 'volcano', name: 'Volcano', emoji: '🌋', tier: 2 } },
  { ingredients: ['Mist', 'Mist'], result: { id: 'fog', name: 'Fog', emoji: '🌫️', tier: 2 } },
  { ingredients: ['Lake', 'Sun'], result: { id: 'evaporation', name: 'Evaporation', emoji: '💨', tier: 2 } },
  { ingredients: ['Earth', 'Rain'], result: { id: 'plant', name: 'Plant', emoji: '🌱', tier: 2 } },
  { ingredients: ['Plant', 'Sun'], result: { id: 'flower', name: 'Flower', emoji: '🌸', tier: 2 } },
  { ingredients: ['Plant', 'Water'], result: { id: 'tree', name: 'Tree', emoji: '🌳', tier: 2 } },

  // Tier 3 - Tertiary & Interdependencies
  { ingredients: ['Water', 'Lake'], result: { id: 'ocean', name: 'Ocean', emoji: '🌊', tier: 3 } },
  { ingredients: ['Earth', 'Mountain'], result: { id: 'range', name: 'Range', emoji: '🏔️', tier: 3 } },
  { ingredients: ['Earth', 'Dust'], result: { id: 'sand', name: 'Sand', emoji: '🏖️', tier: 3 } },
  { ingredients: ['Sand', 'Fire'], result: { id: 'glass', name: 'Glass', emoji: '🍷', tier: 3 } },
  { ingredients: ['Sand', 'Water'], result: { id: 'beach', name: 'Beach', emoji: '🏝️', tier: 3 } },
  { ingredients: ['Earth', 'Lava'], result: { id: 'stone', name: 'Stone', emoji: '🪨', tier: 3 } },
  { ingredients: ['Stone', 'Fire'], result: { id: 'metal', name: 'Metal', emoji: '🤘', tier: 3 } },
  { ingredients: ['Stone', 'Water'], result: { id: 'pebble', name: 'Pebble', emoji: '🌑', tier: 3 } },
  { ingredients: ['Stone', 'Air'], result: { id: 'sandstone', name: 'Sandstone', emoji: '🏜️', tier: 3 } },
  { ingredients: ['Lava', 'Water'], result: { id: 'obsidian', name: 'Obsidian', emoji: '🖤', tier: 3 } },
  { ingredients: ['Lava', 'Air'], result: { id: 'stone', name: 'Stone', emoji: '🪨', tier: 3 } },
  { ingredients: ['Steam', 'Air'], result: { id: 'cloud', name: 'Cloud', emoji: '☁️', tier: 3 } },
  { ingredients: ['Smoke', 'Air'], result: { id: 'mist', name: 'Mist', emoji: '🌫️', tier: 3 } },
  { ingredients: ['Steam', 'Fire'], result: { id: 'energy', name: 'Energy', emoji: '⚡', tier: 3 } },
  { ingredients: ['Smoke', 'Water'], result: { id: 'acid_rain', name: 'Acid Rain', emoji: '🧪', tier: 3 } },

  // Tier 4 - Advanced
  { ingredients: ['Wind', 'Dust'], result: { id: 'storm', name: 'Storm', emoji: '⛈️', tier: 4 } },
  { ingredients: ['Storm', 'Water'], result: { id: 'hurricane', name: 'Hurricane', emoji: '🌀', tier: 4 } },
  { ingredients: ['Fire', 'Sun'], result: { id: 'solar_flare', name: 'Solar Flare', emoji: '💥', tier: 4 } },
  { ingredients: ['Earth', 'Plant'], result: { id: 'soil', name: 'Soil', emoji: '💩', tier: 4 } },
  { ingredients: ['Soil', 'Water'], result: { id: 'swamp', name: 'Swamp', emoji: '🐊', tier: 4 } },
  { ingredients: ['Swamp', 'Fire'], result: { id: 'peat', name: 'Peat', emoji: '🪨', tier: 4 } },
  { ingredients: ['Peat', 'Earth'], result: { id: 'coal', name: 'Coal', emoji: '⬛', tier: 4 } },
  { ingredients: ['Coal', 'Fire'], result: { id: 'diamond', name: 'Diamond', emoji: '💎', tier: 4 } },
  { ingredients: ['Metal', 'Fire'], result: { id: 'steel', name: 'Steel', emoji: '🏗️', tier: 4 } },
  { ingredients: ['Tree', 'Fire'], result: { id: 'charcoal', name: 'Charcoal', emoji: '🪵', tier: 4 } },
  { ingredients: ['Energy', 'Metal'], result: { id: 'electricity', name: 'Electricity', emoji: '🔌', tier: 4 } },
  { ingredients: ['Electricity', 'Glass'], result: { id: 'light_bulb', name: 'Light Bulb', emoji: '💡', tier: 4 } },
  { ingredients: ['Light_Bulb', 'Metal'], result: { id: 'lamp', name: 'Lamp', emoji: '🏮', tier: 4 } },
  { ingredients: ['Electricity', 'Metal'], result: { id: 'wire', name: 'Wire', emoji: '🧵', tier: 4 } },
  { ingredients: ['Wire', 'Glass'], result: { id: 'fiber_optics', name: 'Fiber Optics', emoji: '✨', tier: 4 } },

  // More Interdependencies
  { ingredients: ['Lava', 'Lava'], result: { id: 'volcano', name: 'Volcano', emoji: '🌋', tier: 2 } },
  { ingredients: ['Steam', 'Steam'], result: { id: 'cloud', name: 'Cloud', emoji: '☁️', tier: 2 } },
  { ingredients: ['Smoke', 'Smoke'], result: { id: 'cloud', name: 'Cloud', emoji: '☁️', tier: 2 } },
  { ingredients: ['Mist', 'Mist'], result: { id: 'fog', name: 'Fog', emoji: '🌫️', tier: 2 } },
  { ingredients: ['Lake', 'Lake'], result: { id: 'sea', name: 'Sea', emoji: '🌊', tier: 3 } },
  { ingredients: ['Sea', 'Sea'], result: { id: 'ocean', name: 'Ocean', emoji: '🌊', tier: 3 } },
  { ingredients: ['Sun', 'Sun'], result: { id: 'star', name: 'Star', emoji: '⭐', tier: 3 } },
  { ingredients: ['Star', 'Star'], result: { id: 'galaxy', name: 'Galaxy', emoji: '🌌', tier: 4 } },
  { ingredients: ['Galaxy', 'Galaxy'], result: { id: 'universe', name: 'Universe', emoji: '🌌', tier: 5 } },
  { ingredients: ['Universe', 'Universe'], result: { id: 'multiverse', name: 'Multiverse', emoji: '🌌', tier: 6 } },

  // Life & Nature
  { ingredients: ['Swamp', 'Energy'], result: { id: 'life', name: 'Life', emoji: '🧬', tier: 5 } },
  { ingredients: ['Life', 'Earth'], result: { id: 'human', name: 'Human', emoji: '🧑', tier: 6 } },
  { ingredients: ['Life', 'Water'], result: { id: 'fish', name: 'Fish', emoji: '🐟', tier: 6 } },
  { ingredients: ['Life', 'Air'], result: { id: 'bird', name: 'Bird', emoji: '🐦', tier: 6 } },
  { ingredients: ['Human', 'Human'], result: { id: 'family', name: 'Family', emoji: '👨‍👩‍👧‍👦', tier: 7 } },
  { ingredients: ['Human', 'Metal'], result: { id: 'tool', name: 'Tool', emoji: '🛠️', tier: 7 } },
  { ingredients: ['Tool', 'Metal'], result: { id: 'machine', name: 'Machine', emoji: '⚙️', tier: 8 } },
  { ingredients: ['Machine', 'Electricity'], result: { id: 'robot', name: 'Robot', emoji: '🤖', tier: 9 } },
  { ingredients: ['Robot', 'Life'], result: { id: 'cyborg', name: 'Cyborg', emoji: '🦾', tier: 10 } },

  // Environment
  { ingredients: ['Human', 'Earth'], result: { id: 'farmer', name: 'Farmer', emoji: '👨‍🌾', tier: 7 } },
  { ingredients: ['Farmer', 'Plant'], result: { id: 'food', name: 'Food', emoji: '🍎', tier: 8 } },
  { ingredients: ['Human', 'Stone'], result: { id: 'statue', name: 'Statue', emoji: '🗿', tier: 7 } },
  { ingredients: ['Human', 'Brick'], result: { id: 'house', name: 'House', emoji: '🏠', tier: 7 } },
  { ingredients: ['House', 'House'], result: { id: 'village', name: 'Village', emoji: '🏘️', tier: 8 } },
  { ingredients: ['Village', 'Village'], result: { id: 'city', name: 'City', emoji: '🏙️', tier: 9 } },
  { ingredients: ['City', 'City'], result: { id: 'metropolis', name: 'Metropolis', emoji: '🌇', tier: 10 } },

  // Space
  { ingredients: ['Sun', 'Earth'], result: { id: 'day', name: 'Day', emoji: '☀️', tier: 4 } },
  { ingredients: ['Sun', 'Moon'], result: { id: 'eclipse', name: 'Eclipse', emoji: '🌑', tier: 5 } },
  { ingredients: ['Earth', 'Star'], result: { id: 'moon', name: 'Moon', emoji: '🌙', tier: 4 } },
  { ingredients: ['Moon', 'Water'], result: { id: 'tide', name: 'Tide', emoji: '🌊', tier: 5 } },
  { ingredients: ['Moon', 'Earth'], result: { id: 'night', name: 'Night', emoji: '🌙', tier: 5 } },

  // Abstract
  { ingredients: ['Human', 'Sun'], result: { id: 'hope', name: 'Hope', emoji: '✨', tier: 7 } },
  { ingredients: ['Human', 'Night'], result: { id: 'dream', name: 'Dream', emoji: '💤', tier: 8 } },
  { ingredients: ['Dream', 'Night'], result: { id: 'nightmare', name: 'Nightmare', emoji: '👹', tier: 9 } },
  { ingredients: ['Hope', 'Dream'], result: { id: 'future', name: 'Future', emoji: '🚀', tier: 10 } },
  
  // Artificial Progression
  { ingredients: ['Machine', 'Electricity'], result: { id: 'computer', name: 'Computer', emoji: '💻', tier: 9 } },
  { ingredients: ['Computer', 'Energy'], result: { id: 'internet', name: 'Internet', emoji: '🌐', tier: 10 } },
  { ingredients: ['Computer', 'Life'], result: { id: 'artificial_intelligence', name: 'Artificial Intelligence', emoji: '🧠', tier: 11 } },
  { ingredients: ['Artificial_Intelligence', 'Future'], result: { id: 'singularity', name: 'Singularity', emoji: '🌌', tier: 12 } },
  { ingredients: ['Artificial_Intelligence', 'Robot'], result: { id: 'android', name: 'Android', emoji: '🤖', tier: 12 } },

  // New Progression - Animals & Mythology
  { ingredients: ['Plant', 'Earth'], result: { id: 'grass', name: 'Grass', emoji: '🌿', tier: 3 } },
  { ingredients: ['Swamp', 'Life'], result: { id: 'lizard', name: 'Lizard', emoji: '🦎', tier: 6 } },
  { ingredients: ['Lizard', 'Fire'], result: { id: 'dragon', name: 'Dragon', emoji: '🐉', tier: 7 } },
  { ingredients: ['Human', 'Bird'], result: { id: 'angel', name: 'Angel', emoji: '😇', tier: 7 } },
  { ingredients: ['Human', 'Fire'], result: { id: 'cook', name: 'Cook', emoji: '👨‍🍳', tier: 7 } },
  { ingredients: ['Cook', 'Food'], result: { id: 'meal', name: 'Meal', emoji: '🍱', tier: 9 } },
  { ingredients: ['Meal', 'Family'], result: { id: 'feast', name: 'Feast', emoji: '🍖', tier: 10 } },
  { ingredients: ['Tool', 'Metal'], result: { id: 'sword', name: 'Sword', emoji: '⚔️', tier: 8 } },
  { ingredients: ['Sword', 'Human'], result: { id: 'warrior', name: 'Warrior', emoji: '🤺', tier: 9 } },
  { ingredients: ['Warrior', 'Sword'], result: { id: 'knight', name: 'Knight', emoji: '🛡️', tier: 10 } },
  { ingredients: ['Life', 'Earth'], result: { id: 'animal', name: 'Animal', emoji: '🐾', tier: 6 } },
  { ingredients: ['Animal', 'Grass'], result: { id: 'cow', name: 'Cow', emoji: '🐄', tier: 7 } },
  { ingredients: ['Cow', 'Human'], result: { id: 'minotaur', name: 'Minotaur', emoji: '🐂', tier: 8 } },
  { ingredients: ['Animal', 'Earth'], result: { id: 'horse', name: 'Horse', emoji: '🐎', tier: 7 } },
  { ingredients: ['Horse', 'Human'], result: { id: 'centaur', name: 'Centaur', emoji: '🏹', tier: 8 } },
  { ingredients: ['Human', 'Fish'], result: { id: 'mermaid', name: 'Mermaid', emoji: '🧜‍♀️', tier: 7 } },
  { ingredients: ['Human', 'Lake'], result: { id: 'sailor', name: 'Sailor', emoji: '⛵', tier: 7 } },
  { ingredients: ['Tree', 'Tool'], result: { id: 'wood', name: 'Wood', emoji: '🪵', tier: 8 } },
  { ingredients: ['Wood', 'Tool'], result: { id: 'boat', name: 'Boat', emoji: '🛶', tier: 9 } },
  { ingredients: ['Boat', 'Ocean'], result: { id: 'ship', name: 'Ship', emoji: '🚢', tier: 10 } },
  { ingredients: ['Ship', 'Wind'], result: { id: 'sailboat', name: 'Sailboat', emoji: '⛵', tier: 11 } },
  { ingredients: ['Metal', 'Fire'], result: { id: 'gold', name: 'Gold', emoji: '💰', tier: 5 } },
  { ingredients: ['Gold', 'Human'], result: { id: 'rich', name: 'Rich', emoji: '🤑', tier: 7 } },
  { ingredients: ['Rich', 'House'], result: { id: 'mansion', name: 'Mansion', emoji: '🏰', tier: 8 } },
  { ingredients: ['Mansion', 'City'], result: { id: 'skyline', name: 'Skyline', emoji: '🏙️', tier: 10 } },
  { ingredients: ['Human', 'Future'], result: { id: 'time_travel', name: 'Time Travel', emoji: '⏳', tier: 11 } },
  { ingredients: ['Time_Travel', 'Clock'], result: { id: 'time_machine', name: 'Time Machine', emoji: '🛸', tier: 12 } },
  { ingredients: ['Metal', 'Glass'], result: { id: 'clock', name: 'Clock', emoji: '⏰', tier: 5 } },
  { ingredients: ['Bird', 'Fire'], result: { id: 'phoenix', name: 'Phoenix', emoji: '🔥', tier: 8 } },
  { ingredients: ['Human', 'Clock'], result: { id: 'old', name: 'Old', emoji: '👴', tier: 7 } },

  // Energy-Based Combinations
  { ingredients: ['Ocean', 'Energy'], result: { id: 'tidal_power', name: 'Tidal Power', emoji: '🌊', tier: 6 } },
  { ingredients: ['Lake', 'Energy'], result: { id: 'hydroelectricity', name: 'Hydroelectricity', emoji: '⚡', tier: 6 } },
  { ingredients: ['Water', 'Energy'], result: { id: 'electrolysis', name: 'Electrolysis', emoji: '🧪', tier: 6 } },
  { ingredients: ['Sun', 'Energy'], result: { id: 'solar_power', name: 'Solar Power', emoji: '☀️', tier: 6 } },
  { ingredients: ['Solar_Flare', 'Energy'], result: { id: 'plasma', name: 'Plasma', emoji: '✨', tier: 7 } },
  { ingredients: ['Steam', 'Energy'], result: { id: 'turbine', name: 'Turbine', emoji: '🎡', tier: 6 } },
  { ingredients: ['Fire', 'Energy'], result: { id: 'inferno', name: 'Inferno', emoji: '🔥', tier: 6 } },
  { ingredients: ['Dust', 'Energy'], result: { id: 'static_electricity', name: 'Static Electricity', emoji: '⚡', tier: 5 } },
  { ingredients: ['Earth', 'Energy'], result: { id: 'earthquake', name: 'Earthquake', emoji: '🫨', tier: 5 } },
  { ingredients: ['Air', 'Energy'], result: { id: 'lightning', name: 'Lightning', emoji: '⚡', tier: 5 } },
  { ingredients: ['Lightning', 'Energy'], result: { id: 'thunder', name: 'Thunder', emoji: '⛈️', tier: 6 } },
  { ingredients: ['Wind', 'Energy'], result: { id: 'wind_turbine', name: 'Wind Turbine', emoji: '🌬️', tier: 6 } },
  { ingredients: ['Coal', 'Energy'], result: { id: 'power_plant', name: 'Power Plant', emoji: '🏭', tier: 7 } },
  { ingredients: ['Uranium', 'Energy'], result: { id: 'nuclear_power', name: 'Nuclear Power', emoji: '☢️', tier: 8 } },
  { ingredients: ['Metal', 'Energy'], result: { id: 'battery', name: 'Battery', emoji: '🔋', tier: 6 } },
  { ingredients: ['Battery', 'Energy'], result: { id: 'supercharger', name: 'Supercharger', emoji: '🏎️', tier: 8 } },
  { ingredients: ['Life', 'Energy'], result: { id: 'soul', name: 'Soul', emoji: '👻', tier: 7 } },
  { ingredients: ['Soul', 'Energy'], result: { id: 'spirit', name: 'Spirit', emoji: '✨', tier: 8 } },
  { ingredients: ['Computer', 'Energy'], result: { id: 'server', name: 'Server', emoji: '🖥️', tier: 10 } },
  { ingredients: ['Server', 'Energy'], result: { id: 'data_center', name: 'Data Center', emoji: '🏢', tier: 11 } },
  { ingredients: ['Robot', 'Energy'], result: { id: 'cyborg', name: 'Cyborg', emoji: '🦾', tier: 10 } },
  { ingredients: ['Android', 'Energy'], result: { id: 'super_android', name: 'Super Android', emoji: '🤖', tier: 13 } },
  { ingredients: ['Future', 'Energy'], result: { id: 'fusion', name: 'Fusion', emoji: '⚛️', tier: 12 } },
  { ingredients: ['Fusion', 'Energy'], result: { id: 'star_power', name: 'Star Power', emoji: '🌟', tier: 13 } },
  { ingredients: ['Space', 'Energy'], result: { id: 'vacuum_energy', name: 'Vacuum Energy', emoji: '🌌', tier: 10 } },
  { ingredients: ['Galaxy', 'Energy'], result: { id: 'quasar', name: 'Quasar', emoji: '💫', tier: 11 } },
  { ingredients: ['Universe', 'Energy'], result: { id: 'big_bang', name: 'Big Bang', emoji: '💥', tier: 12 } },
  { ingredients: ['Stone', 'Energy'], result: { id: 'magnet', name: 'Magnet', emoji: '🧲', tier: 5 } },
  { ingredients: ['Magnet', 'Energy'], result: { id: 'electromagnet', name: 'Electromagnet', emoji: '🧲', tier: 7 } },
  { ingredients: ['Sand', 'Energy'], result: { id: 'silicon', name: 'Silicon', emoji: '💎', tier: 6 } },

  // User Requested Combinations
  { ingredients: ['Cyborg', 'Dream'], result: { id: 'techno_dream', name: 'Techno Dream', emoji: '💭', tier: 11 } },
  { ingredients: ['Cyborg', 'Dust'], result: { id: 'nanobots', name: 'Nanobots', emoji: '🦠', tier: 11 } },
  { ingredients: ['Cyborg', 'Earth'], result: { id: 'techno_golem', name: 'Techno Golem', emoji: '🗿', tier: 11 } },
  { ingredients: ['Data_Center', 'Data_Center'], result: { id: 'cloud_network', name: 'Cloud Network', emoji: '🌐', tier: 12 } },
  { ingredients: ['Data_Center', 'Day'], result: { id: 'global_web', name: 'Global Web', emoji: '🌍', tier: 12 } },
  { ingredients: ['Data_Center', 'Diamond'], result: { id: 'quantum_computer', name: 'Quantum Computer', emoji: '💠', tier: 12 } },
  { ingredients: ['Data_Center', 'Dragon'], result: { id: 'digital_dragon', name: 'Digital Dragon', emoji: '🐉', tier: 12 } },
  { ingredients: ['Data_Center', 'Dream'], result: { id: 'virtual_reality', name: 'Virtual Reality', emoji: '🥽', tier: 12 } },
  { ingredients: ['Data_Center', 'Dust'], result: { id: 'hardware_failure', name: 'Hardware Failure', emoji: '⚠️', tier: 12 } },
  { ingredients: ['Data_Center', 'Earth'], result: { id: 'underground_server', name: 'Underground Server', emoji: '🖥️', tier: 12 } },
  { ingredients: ['Day', 'Day'], result: { id: 'summer', name: 'Summer', emoji: '🏖️', tier: 5 } },
  { ingredients: ['Day', 'Diamond'], result: { id: 'sparkle', name: 'Sparkle', emoji: '✨', tier: 5 } },
  { ingredients: ['Day', 'Dragon'], result: { id: 'sun_dragon', name: 'Sun Dragon', emoji: '🐉', tier: 8 } },
  { ingredients: ['Day', 'Dream'], result: { id: 'daydream', name: 'Daydream', emoji: '💭', tier: 9 } },
  { ingredients: ['Day', 'Dust'], result: { id: 'haze', name: 'Haze', emoji: '🌫️', tier: 5 } },
  { ingredients: ['Day', 'Earth'], result: { id: 'land', name: 'Land', emoji: '🌍', tier: 5 } },
  { ingredients: ['Diamond', 'Diamond'], result: { id: 'brilliant', name: 'Brilliant', emoji: '💎', tier: 5 } },
  { ingredients: ['Diamond', 'Dragon'], result: { id: 'crystal_dragon', name: 'Crystal Dragon', emoji: '🐉', tier: 8 } },
  { ingredients: ['Diamond', 'Dream'], result: { id: 'fantasy', name: 'Fantasy', emoji: '🦄', tier: 9 } },
  { ingredients: ['Diamond', 'Dust'], result: { id: 'polishing', name: 'Polishing', emoji: '✨', tier: 5 } },
  { ingredients: ['Diamond', 'Earth'], result: { id: 'mine', name: 'Mine', emoji: '⛏️', tier: 5 } },
  { ingredients: ['Dragon', 'Dragon'], result: { id: 'dragon_egg', name: 'Dragon Egg', emoji: '🥚', tier: 8 } },
  { ingredients: ['Dragon', 'Dream'], result: { id: 'nightmare', name: 'Nightmare', emoji: '👹', tier: 9 } },
  { ingredients: ['Dragon', 'Dust'], result: { id: 'ash', name: 'Ash', emoji: '🚬', tier: 8 } },
  { ingredients: ['Dragon', 'Earth'], result: { id: 'cave', name: 'Cave', emoji: '🕳️', tier: 8 } },
  { ingredients: ['Dream', 'Dream'], result: { id: 'lucid_dream', name: 'Lucid Dream', emoji: '💭', tier: 9 } },
  { ingredients: ['Dream', 'Dust'], result: { id: 'sandman', name: 'Sandman', emoji: '⏳', tier: 9 } },
  { ingredients: ['Dream', 'Earth'], result: { id: 'reality', name: 'Reality', emoji: '🌍', tier: 9 } },
  { ingredients: ['Dust', 'Dust'], result: { id: 'dust_bunny', name: 'Dust Bunny', emoji: '🐰', tier: 4 } }
];
