import { Recipe } from '../types';

export const recipes: Recipe[] = [
  // Acid Rain Combinations
  { ingredients: ['Acid_Rain', 'Acid_Rain'], result: { id: 'toxic_waste', name: 'Toxic Waste', emoji: '☣️', tier: 4 } },
  { ingredients: ['Acid_Rain', 'Air'], result: { id: 'smog', name: 'Smog', emoji: '🌫️', tier: 4 } },
  { ingredients: ['Acid_Rain', 'Android'], result: { id: 'corroded_android', name: 'CorrodedDroid', emoji: '🤖', tier: 13 } },
  { ingredients: ['Acid_Rain', 'Angel'], result: { id: 'fallen_angel', name: 'Fallen Angel', emoji: '🖤', tier: 8 } },
  { ingredients: ['Acid_Rain', 'Animal'], result: { id: 'mutation', name: 'Mutation', emoji: '🧬', tier: 7 } },
  { ingredients: ['Acid_Rain', 'Artificial_Intelligence'], result: { id: 'corrupted_ai', name: 'Corrupted AI', emoji: '👾', tier: 12 } },
  { ingredients: ['Acid_Rain', 'Battery'], result: { id: 'chemical_leak', name: 'Chemical Leak', emoji: '🧪', tier: 7 } },
  { ingredients: ['Acid_Rain', 'Beach'], result: { id: 'polluted_beach', name: 'Polluted Beach', emoji: '🏖️', tier: 4 } },
  { ingredients: ['Acid_Rain', 'Big_Bang'], result: { id: 'toxic_universe', name: 'Toxic Universe', emoji: '🌌', tier: 13 } },
  { ingredients: ['Acid_Rain', 'Bird'], result: { id: 'sick_bird', name: 'Sick Bird', emoji: '🤢', tier: 7 } },
  { ingredients: ['Acid_Rain', 'Boat'], result: { id: 'rusty_boat', name: 'Rusty Boat', emoji: '🛶', tier: 10 } },
  { ingredients: ['Acid_Rain', 'Brick'], result: { id: 'eroded_brick', name: 'Eroded Brick', emoji: '🧱', tier: 3 } },
  { ingredients: ['Acid_Rain', 'Centaur'], result: { id: 'poisoned_centaur', name: 'Poison Centaur', emoji: '🏹', tier: 9 } },
  { ingredients: ['Acid_Rain', 'Charcoal'], result: { id: 'toxic_smoke', name: 'Toxic Smoke', emoji: '💨', tier: 5 } },
  { ingredients: ['Acid_Rain', 'City'], result: { id: 'industrial_city', name: 'Factory City', emoji: '🏭', tier: 10 } },
  { ingredients: ['Acid_Rain', 'Clock'], result: { id: 'corroded_clock', name: 'Corroded Clock', emoji: '⏰', tier: 6 } },
  { ingredients: ['Acid_Rain', 'Cloud'], result: { id: 'toxic_cloud', name: 'Toxic Cloud', emoji: '☁️', tier: 4 } },
  { ingredients: ['Acid_Rain', 'Coal'], result: { id: 'sulfur', name: 'Sulfur', emoji: '🟡', tier: 5 } },
  { ingredients: ['Acid_Rain', 'Computer'], result: { id: 'hardware_damage', name: 'Hard Damage', emoji: '💻', tier: 10 } },
  { ingredients: ['Acid_Rain', 'Cook'], result: { id: 'toxic_food', name: 'Toxic Food', emoji: '🤢', tier: 8 } },
  { ingredients: ['Acid_Rain', 'Cow'], result: { id: 'sick_cow', name: 'Sick Cow', emoji: '🐄', tier: 8 } },
  { ingredients: ['Acid_Rain', 'Cyborg'], result: { id: 'malfunctioning_cyborg', name: 'Broken Cyborg', emoji: '🦾', tier: 11 } },
  { ingredients: ['Acid_Rain', 'Data_Center'], result: { id: 'server_failure', name: 'Server Failure', emoji: '🖥️', tier: 12 } },
  { ingredients: ['Acid_Rain', 'Day'], result: { id: 'gloomy_day', name: 'Gloomy Day', emoji: '☁️', tier: 5 } },
  { ingredients: ['Acid_Rain', 'Diamond'], result: { id: 'dull_diamond', name: 'Dull Diamond', emoji: '💎', tier: 5 } },
  { ingredients: ['Acid_Rain', 'Dragon'], result: { id: 'poison_dragon', name: 'Poison Dragon', emoji: '🐉', tier: 8 } },
  { ingredients: ['Acid_Rain', 'Dream'], result: { id: 'toxic_dream', name: 'Toxic Dream', emoji: '💤', tier: 9 } },
  { ingredients: ['Acid_Rain', 'Dust'], result: { id: 'toxic_dust', name: 'Toxic Dust', emoji: '🧹', tier: 2 } },
  { ingredients: ['Acid_Rain', 'Air_Battery'], result: { id: 'acid_battery', name: 'Acid Battery', emoji: '🔋', tier: 8 } },
  { ingredients: ['Acid_Rain', 'Airboat'], result: { id: 'corroded_airboat', name: 'Corroded Airboat', emoji: '🛶', tier: 11 } },
  { ingredients: ['Acid_Rain', 'Aroma'], result: { id: 'foul_odor', name: 'Foul Odor', emoji: '👃', tier: 6 } },
  { ingredients: ['Acid_Rain', 'Artificial_Intelligence'], result: { id: 'corrupted_ai', name: 'Corrupted AI', emoji: '👾', tier: 12 } },
  { ingredients: ['Acid_Rain', 'Ash'], result: { id: 'acid_ash', name: 'Acid Ash', emoji: '🌋', tier: 4 } },
  { ingredients: ['Acid_Rain', 'Atmosphere'], result: { id: 'polluted_atmosphere', name: 'Bad Atmosphere', emoji: '🌍', tier: 7 } },
  { ingredients: ['Acid_Rain', 'Big_Bang'], result: { id: 'toxic_universe', name: 'Toxic Universe', emoji: '🌌', tier: 13 } },
  { ingredients: ['Acid_Rain', 'Brilliant'], result: { id: 'dim_light', name: 'Dim Light', emoji: '💡', tier: 6 } },
  { ingredients: ['Acid_Rain', 'Carbon_Dioxide'], result: { id: 'acidic_co2', name: 'Acidic CO2', emoji: '💨', tier: 5 } },
  { ingredients: ['Acid_Rain', 'Cave'], result: { id: 'eroded_cave', name: 'Eroded Cave', emoji: '🕳️', tier: 5 } },
  { ingredients: ['Acid_Rain', 'Chemical_Leak'], result: { id: 'toxic_spill', name: 'Toxic Spill', emoji: '☣️', tier: 8 } },
  { ingredients: ['Acid_Rain', 'Cloud_AI'], result: { id: 'corrupted_cloud_ai', name: 'Cloud AI Bad', emoji: '☁️', tier: 13 } },

  { ingredients: ['Air', 'Air_Battery'], result: { id: 'wind_power', name: 'Wind Power', emoji: '🌬️', tier: 6 } },
  { ingredients: ['Air', 'Airboat'], result: { id: 'hovercraft', name: 'Hovercraft', emoji: '🛶', tier: 11 } },
  { ingredients: ['Air', 'Aroma'], result: { id: 'breeze', name: 'Breeze', emoji: '🍃', tier: 4 } },
  { ingredients: ['Air', 'Artificial_Intelligence'], result: { id: 'virtual_assistant', name: 'Virt Assistant', emoji: '🤖', tier: 11 } },
  { ingredients: ['Air', 'Ash'], result: { id: 'volcanic_ash', name: 'Volcanic Ash', emoji: '🌋', tier: 3 } },
  { ingredients: ['Air', 'Atmosphere'], result: { id: 'stratosphere', name: 'Stratosphere', emoji: '🌍', tier: 6 } },
  { ingredients: ['Air', 'Big_Bang'], result: { id: 'cosmic_wind', name: 'Cosmic Wind', emoji: '🌌', tier: 14 } },
  { ingredients: ['Air', 'Brilliant'], result: { id: 'glowing_air', name: 'Glowing Air', emoji: '✨', tier: 7 } },
  { ingredients: ['Air', 'Carbon_Dioxide'], result: { id: 'polluted_air', name: 'Polluted Air', emoji: '💨', tier: 4 } },
  { ingredients: ['Air', 'Cave'], result: { id: 'drafty_cave', name: 'Drafty Cave', emoji: '🕳️', tier: 4 } },
  { ingredients: ['Air', 'Chemical_Leak'], result: { id: 'toxic_fumes', name: 'Toxic Fumes', emoji: '☣️', tier: 7 } },
  { ingredients: ['Air', 'Cloud_AI'], result: { id: 'ai_cloud', name: 'AI Cloud', emoji: '☁️', tier: 13 } },
  { ingredients: ['Air', 'City'], result: { id: 'sky_city', name: 'Sky City', emoji: '🏙️', tier: 10 } },
  { ingredients: ['Air', 'Clock'], result: { id: 'time', name: 'Time', emoji: '⏰', tier: 6 } },
  { ingredients: ['Air', 'Cloud'], result: { id: 'sky', name: 'Sky', emoji: '🌌', tier: 3 } },
  { ingredients: ['Air', 'Coal'], result: { id: 'carbon_dioxide', name: 'Carbon Dioxide', emoji: '💨', tier: 5 } },
  { ingredients: ['Air', 'Computer'], result: { id: 'laptop', name: 'Laptop', emoji: '💻', tier: 10 } },
  { ingredients: ['Air', 'Cook'], result: { id: 'aroma', name: 'Aroma', emoji: '👃', tier: 8 } },
  { ingredients: ['Air', 'Cow'], result: { id: 'flying_cow', name: 'Flying Cow', emoji: '🐄', tier: 8 } },
  { ingredients: ['Air', 'Cyborg'], result: { id: 'jetpack', name: 'Jetpack', emoji: '🚀', tier: 11 } },
  { ingredients: ['Air', 'Data_Center'], result: { id: 'cloud_computing', name: 'Cloud Compute', emoji: '☁️', tier: 12 } },
  { ingredients: ['Air', 'Day'], result: { id: 'atmosphere', name: 'Atmosphere', emoji: '🌍', tier: 5 } },
  { ingredients: ['Air', 'Diamond'], result: { id: 'diamond_dust', name: 'Diamond Dust', emoji: '💎', tier: 5 } },
  { ingredients: ['Air', 'Dragon'], result: { id: 'sky_dragon', name: 'Sky Dragon', emoji: '🐉', tier: 8 } },
  { ingredients: ['Air', 'Dream'], result: { id: 'cloud_nine', name: 'Cloud Nine', emoji: '☁️', tier: 9 } },
  { ingredients: ['Air_Battery', 'Air_Battery'], result: { id: 'super_battery', name: 'Super Battery', emoji: '🔋', tier: 10 } },
  { ingredients: ['Air_Battery', 'Airboat'], result: { id: 'electric_airboat', name: 'Elec Airboat', emoji: '🛶', tier: 12 } },
  { ingredients: ['Air_Battery', 'Android'], result: { id: 'charged_android', name: 'ChargedDroid', emoji: '🤖', tier: 14 } },
  { ingredients: ['Air_Battery', 'Angel'], result: { id: 'electric_angel', name: 'Electric Angel', emoji: '⚡', tier: 10 } },
  { ingredients: ['Air_Battery', 'Animal'], result: { id: 'electric_animal', name: 'Elec Animal', emoji: '🐾', tier: 9 } },
  { ingredients: ['Air_Battery', 'Aroma'], result: { id: 'ozone', name: 'Ozone', emoji: '🌬️', tier: 7 } },
  { ingredients: ['Air_Battery', 'Artificial_Intelligence'], result: { id: 'ai_battery', name: 'AI Battery', emoji: '🧠', tier: 13 } },
  { ingredients: ['Air_Battery', 'Ash'], result: { id: 'ash_battery', name: 'Ash Battery', emoji: '🌋', tier: 5 } },
  { ingredients: ['Air_Battery', 'Atmosphere'], result: { id: 'ionosphere', name: 'Ionosphere', emoji: '🌍', tier: 8 } },
  { ingredients: ['Air_Battery', 'Battery'], result: { id: 'power_bank', name: 'Power Bank', emoji: '🔋', tier: 8 } },
  { ingredients: ['Air_Battery', 'Beach'], result: { id: 'electric_beach', name: 'Electric Beach', emoji: '🏖️', tier: 6 } },
  { ingredients: ['Air_Battery', 'Big_Bang'], result: { id: 'cosmic_battery', name: 'Cosmic Battery', emoji: '🌌', tier: 15 } },
  { ingredients: ['Air_Battery', 'Bird'], result: { id: 'electric_bird', name: 'Electric Bird', emoji: '🐦', tier: 9 } },
  { ingredients: ['Air_Battery', 'Boat'], result: { id: 'electric_boat', name: 'Electric Boat', emoji: '🛶', tier: 11 } },
  { ingredients: ['Air_Battery', 'Brick'], result: { id: 'electric_brick', name: 'Electric Brick', emoji: '🧱', tier: 5 } },
  { ingredients: ['Air_Battery', 'Brilliant'], result: { id: 'lightning_bolt', name: 'Lightning Bolt', emoji: '⚡', tier: 9 } },
  { ingredients: ['Air_Battery', 'Carbon_Dioxide'], result: { id: 'co2_battery', name: 'CO2 Battery', emoji: '💨', tier: 6 } },
  { ingredients: ['Air_Battery', 'Cave'], result: { id: 'electric_cave', name: 'Electric Cave', emoji: '🕳️', tier: 6 } },
  { ingredients: ['Air_Battery', 'Centaur'], result: { id: 'electric_centaur', name: 'Elec Centaur', emoji: '🏹', tier: 11 } },
  { ingredients: ['Air_Battery', 'Charcoal'], result: { id: 'carbon_battery', name: 'Carbon Battery', emoji: '🔋', tier: 7 } },
  { ingredients: ['Air_Battery', 'Chemical_Leak'], result: { id: 'toxic_battery', name: 'Toxic Battery', emoji: '☣️', tier: 9 } },
  { ingredients: ['Air_Battery', 'City'], result: { id: 'power_grid', name: 'Power Grid', emoji: '🏙️', tier: 12 } },
  { ingredients: ['Air_Battery', 'Clock'], result: { id: 'electric_clock', name: 'Electric Clock', emoji: '⏰', tier: 8 } },
  { ingredients: ['Air_Battery', 'Cloud'], result: { id: 'thunderstorm', name: 'Thunderstorm', emoji: '⚡', tier: 6 } },
  { ingredients: ['AI_Cloud', 'AI_Cloud'], result: { id: 'super_ai_cloud', name: 'Super AI Cloud', emoji: '☁️', tier: 15 } },
  { ingredients: ['AI_Cloud', 'Acid_Ash'], result: { id: 'toxic_ai_cloud', name: 'Toxic AI Cloud', emoji: '☣️', tier: 14 } },
  { ingredients: ['AI_Cloud', 'Acid_Battery'], result: { id: 'corrupted_ai_battery', name: 'Corrupted AI Battery', emoji: '🔋', tier: 14 } },
  { ingredients: ['AI_Cloud', 'Acid_Rain'], result: { id: 'corrupted_ai_cloud', name: 'Corrupted AI Cloud', emoji: '☁️', tier: 14 } },
  { ingredients: ['AI_Cloud', 'Acidic_CO2'], result: { id: 'polluted_ai_cloud', name: 'Polluted AI Cloud', emoji: '💨', tier: 13 } },
  { ingredients: ['AI_Cloud', 'Air'], result: { id: 'breezy_ai_cloud', name: 'Breezy AI Cloud', emoji: '🌬️', tier: 13 } },
  { ingredients: ['AI_Cloud', 'Air_Battery'], result: { id: 'electric_ai_cloud', name: 'Electric AI Cloud', emoji: '⚡', tier: 14 } },
  { ingredients: ['AI_Cloud', 'Airboat'], result: { id: 'flying_ai_boat', name: 'Flying AI Boat', emoji: '🛶', tier: 14 } },
  { ingredients: ['AI_Cloud', 'Android'], result: { id: 'android_ai_cloud', name: 'Android AI Cloud', emoji: '🤖', tier: 15 } },
  { ingredients: ['AI_Cloud', 'Angel'], result: { id: 'heavenly_ai_cloud', name: 'Heavenly AI Cloud', emoji: '☁️', tier: 14 } },
  { ingredients: ['AI_Cloud', 'Animal'], result: { id: 'animal_ai_cloud', name: 'Animal AI Cloud', emoji: '🐾', tier: 13 } },
  { ingredients: ['AI_Cloud', 'Aroma'], result: { id: 'scented_ai_cloud', name: 'Scented AI Cloud', emoji: '👃', tier: 13 } },
  { ingredients: ['AI_Cloud', 'Artificial_Intelligence'], result: { id: 'super_ai', name: 'Super AI', emoji: '🧠', tier: 15 } },
  { ingredients: ['AI_Cloud', 'Ash'], result: { id: 'ashy_ai_cloud', name: 'Ashy AI Cloud', emoji: '🌋', tier: 13 } },
  { ingredients: ['AI_Cloud', 'Atmosphere'], result: { id: 'global_ai_cloud', name: 'Global AI Cloud', emoji: '🌍', tier: 14 } },
  { ingredients: ['AI_Cloud', 'Battery'], result: { id: 'battery_ai_cloud', name: 'Battery AI Cloud', emoji: '🔋', tier: 13 } },
  { ingredients: ['AI_Cloud', 'Beach'], result: { id: 'beach_ai_cloud', name: 'Beach AI Cloud', emoji: '🏖️', tier: 13 } },
  { ingredients: ['AI_Cloud', 'Big_Bang'], result: { id: 'cosmic_ai_cloud', name: 'Cosmic AI Cloud', emoji: '🌌', tier: 16 } },
  { ingredients: ['AI_Cloud', 'Bird'], result: { id: 'bird_ai_cloud', name: 'Bird AI Cloud', emoji: '🐦', tier: 13 } },
  { ingredients: ['AI_Cloud', 'Boat'], result: { id: 'boat_ai_cloud', name: 'Boat AI Cloud', emoji: '🛶', tier: 13 } },
  { ingredients: ['AI_Cloud', 'Breeze'], result: { id: 'breezy_ai_cloud', name: 'Breezy AI Cloud', emoji: '🍃', tier: 13 } },
  { ingredients: ['AI_Cloud', 'Brick'], result: { id: 'brick_ai_cloud', name: 'Brick AI Cloud', emoji: '🧱', tier: 13 } },
  { ingredients: ['AI_Cloud', 'Brilliant'], result: { id: 'glowing_ai_cloud', name: 'Glowing AI Cloud', emoji: '✨', tier: 14 } },
  { ingredients: ['AI_Cloud', 'Carbon_Dioxide'], result: { id: 'co2_ai_cloud', name: 'CO2 AI Cloud', emoji: '💨', tier: 13 } },
  { ingredients: ['AI_Cloud', 'Cave'], result: { id: 'cave_ai_cloud', name: 'Cave AI Cloud', emoji: '🕳️', tier: 13 } },
  { ingredients: ['AI_Cloud', 'Centaur'], result: { id: 'centaur_ai_cloud', name: 'Centaur AI Cloud', emoji: '🏹', tier: 14 } },
  { ingredients: ['AI_Battery', 'AI_Battery'], result: { id: 'super_ai_battery', name: 'Super AI Battery', emoji: '🔋', tier: 15 } },
  { ingredients: ['AI_Battery', 'AI_Cloud'], result: { id: 'ai_cloud_battery', name: 'AI Cloud Battery', emoji: '☁️', tier: 14 } },
  { ingredients: ['AI_Battery', 'AI_Cloud'], result: { id: 'ai_cloud_battery', name: 'AI Cloud Battery', emoji: '☁️', tier: 14 } },
  { ingredients: ['AI_Battery', 'Acid_Ash'], result: { id: 'acid_ash_battery', name: 'Acid Ash Battery', emoji: '☣️', tier: 10 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile'], result: { id: 'acid_ash_pile_battery', name: 'Acid Ash Pile Battery', emoji: '☣️', tier: 11 } },
  { ingredients: ['AI_Battery', 'Acid_Battery'], result: { id: 'acid_battery_plus', name: 'Acid Battery Plus', emoji: '☣️', tier: 11 } },
  { ingredients: ['AI_Battery', 'Acid_Rain'], result: { id: 'acid_rain_battery', name: 'Acid Rain Battery', emoji: '☣️', tier: 10 } },
  { ingredients: ['AI_Battery', 'Acid_Sludge'], result: { id: 'acid_sludge_battery', name: 'Acid Sludge Battery', emoji: '☣️', tier: 11 } },
  { ingredients: ['AI_Battery', 'Acid_Ash'], result: { id: 'acid_ash_battery', name: 'Acid Ash Battery', emoji: '☣️', tier: 10 } },
  { ingredients: ['AI_Battery', 'Acid_Battery'], result: { id: 'acid_battery_plus', name: 'Acid Battery Plus', emoji: '☣️', tier: 11 } },
  { ingredients: ['AI_Battery', 'Acid_Rain'], result: { id: 'acid_rain_battery', name: 'Acid Rain Battery', emoji: '☣️', tier: 10 } },
  { ingredients: ['AI_Battery', 'Acidic_CO2'], result: { id: 'acidic_co2_battery', name: 'Acidic CO2 Battery', emoji: '💨', tier: 10 } },
  { ingredients: ['AI_Battery', 'Acidic_CO2'], result: { id: 'acidic_co2_battery', name: 'Acidic CO2 Battery', emoji: '💨', tier: 10 } },
  { ingredients: ['AI_Battery', 'Air'], result: { id: 'air_ai_battery', name: 'Air AI Battery', emoji: '🌬️', tier: 9 } },
  { ingredients: ['AI_Battery', 'Air_Battery'], result: { id: 'super_air_battery', name: 'Super Air Battery', emoji: '🔋', tier: 11 } },
  { ingredients: ['AI_Battery', 'Airboat'], result: { id: 'electric_airboat_battery', name: 'Electric Airboat Battery', emoji: '🛶', tier: 13 } },
  { ingredients: ['AI_Battery', 'Airborne_Ash'], result: { id: 'airborne_ash_battery', name: 'Airborne Ash Battery', emoji: '🌬️', tier: 10 } },
  { ingredients: ['AI_Battery', 'AI_Battery'], result: { id: 'super_ai_battery', name: 'Super AI Battery', emoji: '🔋', tier: 15 } },
  { ingredients: ['AI_Battery', 'AI_Cloud'], result: { id: 'ai_cloud_battery', name: 'AI Cloud Battery', emoji: '☁️', tier: 14 } },
  { ingredients: ['AI_Battery', 'AI_Cloud_Battery'], result: { id: 'ai_cloud_battery_plus', name: 'AI Cloud Battery Plus', emoji: '☁️', tier: 15 } },
  { ingredients: ['AI_Battery', 'AI_Battery'], result: { id: 'super_ai_battery', name: 'Super AI Battery', emoji: '🔋', tier: 15 } },
  { ingredients: ['AI_Battery', 'AI_Cloud'], result: { id: 'ai_cloud_battery', name: 'AI Cloud Battery', emoji: '☁️', tier: 14 } },
  { ingredients: ['AI_Battery', 'Acid_Ash'], result: { id: 'acid_ash_battery', name: 'Acid Ash Battery', emoji: '☣️', tier: 10 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Battery'], result: { id: 'acid_ash_battery_plus', name: 'Acid Ash Battery Plus', emoji: '☣️', tier: 11 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile'], result: { id: 'acid_ash_pile_battery', name: 'Acid Ash Pile Battery', emoji: '☣️', tier: 11 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile_Battery'], result: { id: 'acid_ash_pile_battery_plus', name: 'Acid Ash Pile Battery Plus', emoji: '☣️', tier: 12 } },
  { ingredients: ['AI_Battery', 'Acid_Battery'], result: { id: 'acid_battery_plus', name: 'Acid Battery Plus', emoji: '☣️', tier: 11 } },
  { ingredients: ['AI_Battery', 'Acid_Battery_Plus'], result: { id: 'acid_battery_ultra', name: 'Acid Battery Ultra', emoji: '☣️', tier: 12 } },
  { ingredients: ['AI_Battery', 'Acid_Rain'], result: { id: 'acid_rain_battery', name: 'Acid Rain Battery', emoji: '☣️', tier: 10 } },
  { ingredients: ['AI_Battery', 'Acid_Rain_Battery'], result: { id: 'acid_rain_battery_plus', name: 'Acid Rain Battery Plus', emoji: '☣️', tier: 11 } },
  { ingredients: ['AI_Battery', 'Acid_Sludge'], result: { id: 'acid_sludge_battery', name: 'Acid Sludge Battery', emoji: '☣️', tier: 11 } },
  { ingredients: ['AI_Battery', 'Acid_Sludge_Battery'], result: { id: 'acid_sludge_battery_plus', name: 'Acid Sludge Battery Plus', emoji: '☣️', tier: 12 } },
  { ingredients: ['AI_Battery', 'Acid_Ash'], result: { id: 'acid_ash_battery', name: 'Acid Ash Battery', emoji: '☣️', tier: 10 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile'], result: { id: 'acid_ash_pile_battery', name: 'Acid Ash Pile Battery', emoji: '☣️', tier: 11 } },
  { ingredients: ['AI_Battery', 'Acid_Battery'], result: { id: 'acid_battery_plus', name: 'Acid Battery Plus', emoji: '☣️', tier: 11 } },
  { ingredients: ['AI_Battery', 'Acid_Rain'], result: { id: 'acid_rain_battery', name: 'Acid Rain Battery', emoji: '☣️', tier: 10 } },
  { ingredients: ['AI_Battery', 'Acid_Sludge'], result: { id: 'acid_sludge_battery', name: 'Acid Sludge Battery', emoji: '☣️', tier: 11 } },
  { ingredients: ['AI_Battery', 'Acidic_CO2'], result: { id: 'acidic_co2_battery', name: 'Acidic CO2 Battery', emoji: '💨', tier: 10 } },
  { ingredients: ['AI_Battery', 'Acidic_CO2_Battery'], result: { id: 'acidic_co2_battery_plus', name: 'Acidic CO2 Battery Plus', emoji: '💨', tier: 11 } },
  { ingredients: ['AI_Battery', 'Acidic_CO2'], result: { id: 'acidic_co2_battery', name: 'Acidic CO2 Battery', emoji: '💨', tier: 10 } },
  { ingredients: ['AI_Battery', 'Air'], result: { id: 'air_ai_battery', name: 'Air AI Battery', emoji: '🌬️', tier: 9 } },
  { ingredients: ['AI_Battery', 'Air_AI_Battery'], result: { id: 'air_ai_battery_plus', name: 'Air AI Battery Plus', emoji: '🌬️', tier: 10 } },
  { ingredients: ['AI_Battery', 'Air_Battery'], result: { id: 'super_air_battery', name: 'Super Air Battery', emoji: '🔋', tier: 11 } },
  { ingredients: ['AI_Battery', 'Airboat'], result: { id: 'electric_airboat_battery', name: 'Electric Airboat Battery', emoji: '🛶', tier: 13 } },
  { ingredients: ['AI_Battery', 'Airborne_Ash'], result: { id: 'airborne_ash_battery', name: 'Airborne Ash Battery', emoji: '🌬️', tier: 10 } },
  { ingredients: ['AI_Battery', 'Airborne_Ash_Battery'], result: { id: 'airborne_ash_battery_plus', name: 'Airborne Ash Battery Plus', emoji: '🌬️', tier: 11 } },
  { ingredients: ['AI_Battery', 'Airborne_Ash'], result: { id: 'airborne_ash_battery', name: 'Airborne Ash Battery', emoji: '🌬️', tier: 10 } },
  { ingredients: ['AI_Cloud', 'AI_Cloud'], result: { id: 'super_ai_cloud', name: 'Super AI Cloud', emoji: '☁️', tier: 15 } },
  { ingredients: ['AI_Cloud', 'AI_Cloud_Battery'], result: { id: 'ai_cloud_battery_plus', name: 'AI Cloud Battery Plus', emoji: '☁️', tier: 16 } },
  { ingredients: ['AI_Cloud', 'AI_Battery'], result: { id: 'ai_cloud_battery', name: 'AI Cloud Battery', emoji: '☁️', tier: 14 } },
  { ingredients: ['AI_Cloud', 'AI_Cloud'], result: { id: 'super_ai_cloud', name: 'Super AI Cloud', emoji: '☁️', tier: 15 } },
  { ingredients: ['AI_Cloud', 'Acid_Ash'], result: { id: 'toxic_ai_cloud', name: 'Toxic AI Cloud', emoji: '☣️', tier: 14 } },
  { ingredients: ['AI_Cloud', 'Acid_Ash_Battery'], result: { id: 'toxic_ai_cloud_battery', name: 'Toxic AI Bat', emoji: '☣️', tier: 15 } },
  { ingredients: ['AI_Cloud', 'Acid_Ash_Pile'], result: { id: 'toxic_ai_cloud_pile', name: 'Toxic AI Cloud Pile', emoji: '☣️', tier: 15 } },
  { ingredients: ['AI_Cloud', 'Acid_Ash_Pile_Battery'], result: { id: 'toxic_ai_cloud_pile_battery', name: 'Toxic AI Pile Bat', emoji: '☣️', tier: 16 } },
  { ingredients: ['AI_Cloud', 'Acid_Battery'], result: { id: 'corrupted_ai_battery', name: 'Corrupted AI Battery', emoji: '🔋', tier: 14 } },
  { ingredients: ['AI_Cloud', 'Acid_Battery_Plus'], result: { id: 'corrupted_ai_battery_plus', name: 'Corrupted AI Battery Plus', emoji: '🔋', tier: 15 } },
  { ingredients: ['AI_Cloud', 'Acid_Rain'], result: { id: 'corrupted_ai_cloud', name: 'Corrupted AI Cloud', emoji: '☁️', tier: 14 } },
  { ingredients: ['AI_Cloud', 'Acid_Rain_Battery'], result: { id: 'corrupted_ai_cloud_battery', name: 'Corrupted AI Cloud Battery', emoji: '☁️', tier: 15 } },
  { ingredients: ['AI_Cloud', 'Acid_Sludge'], result: { id: 'polluted_ai_cloud', name: 'Polluted AI Cloud', emoji: '💨', tier: 14 } },
  { ingredients: ['AI_Cloud', 'Acid_Sludge_Battery'], result: { id: 'polluted_ai_cloud_battery', name: 'Polluted AI Cloud Battery', emoji: '💨', tier: 15 } },
  { ingredients: ['AI_Cloud', 'Acid_Ash'], result: { id: 'toxic_ai_cloud', name: 'Toxic AI Cloud', emoji: '☣️', tier: 14 } },
  { ingredients: ['AI_Cloud', 'Acid_Ash_Pile'], result: { id: 'toxic_ai_cloud_pile', name: 'Toxic AI Cloud Pile', emoji: '☣️', tier: 15 } },
  { ingredients: ['AI_Cloud', 'Acid_Battery'], result: { id: 'corrupted_ai_battery', name: 'Corrupted AI Battery', emoji: '🔋', tier: 14 } },
  { ingredients: ['AI_Cloud', 'Acid_Rain'], result: { id: 'corrupted_ai_cloud', name: 'Corrupted AI Cloud', emoji: '☁️', tier: 14 } },
  { ingredients: ['AI_Cloud', 'Acid_Sludge'], result: { id: 'polluted_ai_cloud', name: 'Polluted AI Cloud', emoji: '💨', tier: 14 } },
  { ingredients: ['AI_Cloud', 'Acidic_CO2'], result: { id: 'polluted_ai_cloud', name: 'Polluted AI Cloud', emoji: '💨', tier: 13 } },
  { ingredients: ['AI_Cloud', 'Acidic_CO2_Battery'], result: { id: 'polluted_ai_cloud_battery', name: 'Polluted AI Cloud Battery', emoji: '💨', tier: 14 } },
  { ingredients: ['AI_Cloud', 'Acidic_CO2'], result: { id: 'polluted_ai_cloud', name: 'Polluted AI Cloud', emoji: '💨', tier: 13 } },
  { ingredients: ['AI_Cloud', 'Air'], result: { id: 'breezy_ai_cloud', name: 'Breezy AI Cloud', emoji: '🌬️', tier: 13 } },
  { ingredients: ['AI_Cloud', 'Air_AI_Battery'], result: { id: 'breezy_ai_cloud_battery', name: 'Breezy AI Cloud Battery', emoji: '🌬️', tier: 14 } },
  { ingredients: ['AI_Cloud', 'Air_Battery'], result: { id: 'electric_ai_cloud', name: 'Electric AI Cloud', emoji: '⚡', tier: 14 } },
  { ingredients: ['AI_Cloud', 'Airboat'], result: { id: 'flying_ai_boat', name: 'Flying AI Boat', emoji: '🛶', tier: 14 } },
  { ingredients: ['AI_Cloud', 'Airborne_Ash'], result: { id: 'ashy_ai_cloud', name: 'Ashy AI Cloud', emoji: '🌬️', tier: 13 } },
  { ingredients: ['AI_Cloud', 'Airborne_Ash_Battery'], result: { id: 'ashy_ai_cloud_battery', name: 'Ashy AI Cloud Battery', emoji: '🌬️', tier: 14 } },
  { ingredients: ['AI_Cloud', 'Airborne_Ash'], result: { id: 'ashy_ai_cloud', name: 'Ashy AI Cloud', emoji: '🌬️', tier: 13 } },
  { ingredients: ['AI_Cloud_Battery', 'AI_Cloud_Battery'], result: { id: 'super_ai_cloud_battery', name: 'Super AI Cloud Battery', emoji: '☁️', tier: 17 } },
  { ingredients: ['AI_Cloud_Battery', 'AI_Battery'], result: { id: 'ai_cloud_battery_plus', name: 'AI Cloud Battery Plus', emoji: '☁️', tier: 16 } },
  { ingredients: ['AI_Cloud_Battery', 'AI_Cloud'], result: { id: 'ai_cloud_battery_plus', name: 'AI Cloud Battery Plus', emoji: '☁️', tier: 16 } },
  { ingredients: ['AI_Cloud_Battery', 'Acid_Ash'], result: { id: 'toxic_ai_cloud_battery', name: 'Toxic AI Cloud Battery', emoji: '☣️', tier: 15 } },
  { ingredients: ['AI_Cloud_Battery', 'Acid_Ash_Battery'], result: { id: 'toxic_ai_cloud_battery_plus', name: 'Toxic AI Cloud Battery Plus', emoji: '☣️', tier: 16 } },
  { ingredients: ['AI_Cloud_Battery', 'Acid_Ash_Pile'], result: { id: 'toxic_ai_cloud_pile_battery', name: 'Toxic AI Cloud Pile Battery', emoji: '☣️', tier: 16 } },
  { ingredients: ['AI_Cloud_Battery', 'Acid_Ash_Pile_Battery'], result: { id: 'toxic_ai_cloud_pile_battery_plus', name: 'Toxic AI Cloud Pile Battery Plus', emoji: '☣️', tier: 17 } },
  { ingredients: ['AI_Cloud_Battery', 'Acid_Battery'], result: { id: 'corrupted_ai_battery_plus', name: 'Corrupted AI Battery Plus', emoji: '🔋', tier: 15 } },
  { ingredients: ['AI_Cloud_Battery', 'Acid_Battery_Plus'], result: { id: 'corrupted_ai_battery_ultra', name: 'Corrupted AI Battery Ultra', emoji: '🔋', tier: 16 } },
  { ingredients: ['AI_Cloud_Battery', 'Acid_Rain'], result: { id: 'corrupted_ai_cloud_battery', name: 'Corrupted AI Cloud Battery', emoji: '☁️', tier: 15 } },
  { ingredients: ['AI_Cloud_Battery', 'Acid_Rain_Battery'], result: { id: 'corrupted_ai_cloud_battery_plus', name: 'Corrupted AI Cloud Battery Plus', emoji: '☁️', tier: 16 } },
  { ingredients: ['Acid_Ash_Battery', 'Acid_Ash_Pile'], result: { id: 'acid_ash_pile_battery', name: 'Acid Ash Pile Battery', emoji: '☣️', tier: 12 } },
  { ingredients: ['Acid_Ash_Battery', 'Acid_Ash_Pile_Battery'], result: { id: 'acid_ash_pile_battery_plus', name: 'Ash Pile Battery Plus', emoji: '☣️', tier: 13 } },
  { ingredients: ['Acid_Ash_Battery', 'Acid_Battery'], result: { id: 'acid_battery_plus', name: 'Acid Battery Plus', emoji: '☣️', tier: 11 } },
  { ingredients: ['Acid_Ash_Battery', 'Acid_Battery_Plus'], result: { id: 'acid_battery_ultra', name: 'Acid Battery Ultra', emoji: '☣️', tier: 12 } },
  { ingredients: ['Acid_Ash_Battery', 'Acid_Rain'], result: { id: 'acid_rain_battery', name: 'Acid Rain Battery', emoji: '☣️', tier: 10 } },
  { ingredients: ['Acid_Ash_Battery', 'Acid_Rain_Battery'], result: { id: 'acid_rain_battery_plus', name: 'Acid Rain Battery Plus', emoji: '☣️', tier: 11 } },
  { ingredients: ['Acid_Ash_Pile', 'Acid_Ash_Pile'], result: { id: 'acid_ash_pile_plus', name: 'Acid Ash Pile Plus', emoji: '☣️', tier: 7 } },
  { ingredients: ['Acid_Ash_Pile', 'Acid_Ash_Pile_Battery'], result: { id: 'acid_ash_pile_battery_plus', name: 'Ash Pile Battery Plus', emoji: '☣️', tier: 13 } },
  { ingredients: ['Acid_Ash_Pile', 'Acid_Battery'], result: { id: 'acid_ash_pile_battery', name: 'Acid Ash Pile Battery', emoji: '☣️', tier: 12 } },
  { ingredients: ['Acid_Ash_Pile', 'Acid_Battery_Plus'], result: { id: 'acid_ash_pile_battery_plus', name: 'Ash Pile Battery Plus', emoji: '☣️', tier: 13 } },
  { ingredients: ['Acid_Ash_Pile', 'Acid_Rain'], result: { id: 'acid_ash_pile_rain', name: 'Acid Ash Pile Rain', emoji: '☣️', tier: 7 } },
  { ingredients: ['Acid_Ash_Pile', 'Acid_Rain_Battery'], result: { id: 'acid_ash_pile_rain_battery', name: 'Acid Ash Pile Rain Battery', emoji: '☣️', tier: 11 } },
  { ingredients: ['Acid_Ash_Pile_Battery', 'Acid_Ash_Pile_Battery'], result: { id: 'super_acid_ash_pile_battery', name: 'Super Acid Ash Pile Battery', emoji: '☣️', tier: 18 } },
  { ingredients: ['Acid_Ash_Pile_Battery', 'Acid_Battery'], result: { id: 'acid_ash_pile_battery_plus', name: 'Ash Pile Battery Plus', emoji: '☣️', tier: 13 } },
  { ingredients: ['Acid_Ash_Pile_Battery', 'Acid_Battery_Plus'], result: { id: 'acid_ash_pile_battery_ultra', name: 'Acid Ash Pile Battery Ultra', emoji: '☣️', tier: 14 } },
  { ingredients: ['Acid_Ash_Pile_Battery', 'Acid_Rain'], result: { id: 'acid_ash_pile_rain_battery', name: 'Acid Ash Pile Rain Battery', emoji: '☣️', tier: 12 } },
  { ingredients: ['Acid_Ash_Pile_Battery', 'Acid_Rain_Battery'], result: { id: 'acid_ash_pile_rain_battery_plus', name: 'Acid Ash Pile Rain Battery Plus', emoji: '☣️', tier: 13 } },
  { ingredients: ['Acid_Battery', 'Acid_Battery'], result: { id: 'acid_battery_plus', name: 'Acid Battery Plus', emoji: '☣️', tier: 11 } },
  { ingredients: ['Acid_Battery', 'Acid_Battery_Plus'], result: { id: 'acid_battery_ultra', name: 'Acid Battery Ultra', emoji: '☣️', tier: 12 } },
  { ingredients: ['Acid_Battery', 'Acid_Rain'], result: { id: 'acid_rain_battery', name: 'Acid Rain Battery', emoji: '☣️', tier: 10 } },
  { ingredients: ['Acid_Battery', 'Acid_Rain_Battery'], result: { id: 'acid_rain_battery_plus', name: 'Acid Rain Battery Plus', emoji: '☣️', tier: 11 } },
  { ingredients: ['Acid_Battery_Plus', 'Acid_Battery_Plus'], result: { id: 'acid_battery_ultra', name: 'Acid Battery Ultra', emoji: '☣️', tier: 13 } },
  { ingredients: ['Acid_Battery_Plus', 'Acid_Rain'], result: { id: 'acid_rain_battery_plus', name: 'Acid Rain Battery Plus', emoji: '☣️', tier: 11 } },
  { ingredients: ['Acid_Battery_Plus', 'Acid_Rain_Battery'], result: { id: 'acid_rain_battery_ultra', name: 'Acid Rain Battery Ultra', emoji: '☣️', tier: 12 } },
  { ingredients: ['Acid_Rain', 'Acid_Rain_Battery'], result: { id: 'acid_rain_battery_plus', name: 'Acid Rain Battery Plus', emoji: '☣️', tier: 11 } },
  { ingredients: ['Acid_Rain_Battery', 'Acid_Rain_Battery'], result: { id: 'super_acid_rain_battery', name: 'Super Acid Rain Battery', emoji: '☣️', tier: 12 } },
  { ingredients: ['AI_Battery', 'AI_Battery'], result: { id: 'super_ai_battery', name: 'Super AI Battery', emoji: '🔋', tier: 15 } },
  { ingredients: ['AI_Battery', 'AI_Cloud'], result: { id: 'ai_cloud_battery', name: 'AI Cloud Battery', emoji: '☁️', tier: 14 } },
  { ingredients: ['AI_Battery', 'AI_Cloud_Battery'], result: { id: 'ai_cloud_battery_plus', name: 'AI Cloud Battery Plus', emoji: '☁️', tier: 15 } },
  { ingredients: ['AI_Battery', 'AI_Cloud_Battery_Plus'], result: { id: 'ai_cloud_battery_ultra', name: 'AI Cloud Battery Ultra', emoji: '☁️', tier: 16 } },
  { ingredients: ['AI_Battery', 'Acid_Ash'], result: { id: 'acid_ash_battery', name: 'Acid Ash Battery', emoji: '☣️', tier: 10 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Battery'], result: { id: 'acid_ash_battery_plus', name: 'Acid Ash Battery Plus', emoji: '☣️', tier: 11 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Battery_Plus'], result: { id: 'acid_ash_battery_ultra', name: 'Acid Ash Battery Ultra', emoji: '☣️', tier: 12 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile'], result: { id: 'acid_ash_pile_battery', name: 'Acid Ash Pile Battery', emoji: '☣️', tier: 11 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile_Battery'], result: { id: 'acid_ash_pile_battery_plus', name: 'Acid Ash Pile Battery Plus', emoji: '☣️', tier: 12 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile_Battery_Plus'], result: { id: 'acid_ash_pile_battery_ultra', name: 'Acid Ash Pile Battery Ultra', emoji: '☣️', tier: 13 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile_Battery_Ultra'], result: { id: 'acid_ash_pile_battery_mega', name: 'Acid Ash Pile Battery Mega', emoji: '☣️', tier: 14 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile_Plus'], result: { id: 'acid_ash_pile_plus_battery', name: 'Acid Ash Pile Plus Battery', emoji: '☣️', tier: 12 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile_Rain'], result: { id: 'acid_ash_pile_rain_battery', name: 'Acid Ash Pile Rain Battery', emoji: '☣️', tier: 12 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile_Rain_Battery'], result: { id: 'acid_ash_pile_rain_battery_plus', name: 'Acid Ash Pile Rain Battery Plus', emoji: '☣️', tier: 13 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile_Rain_Battery_Plus'], result: { id: 'acid_ash_pile_rain_battery_ultra', name: 'Acid Ash Pile Rain Battery Ultra', emoji: '☣️', tier: 14 } },
  { ingredients: ['AI_Battery', 'Acid_Battery'], result: { id: 'acid_battery_plus', name: 'Acid Battery Plus', emoji: '☣️', tier: 11 } },
  { ingredients: ['AI_Battery', 'Acid_Battery_Plus'], result: { id: 'acid_battery_ultra', name: 'Acid Battery Ultra', emoji: '☣️', tier: 12 } },
  { ingredients: ['AI_Battery', 'Acid_Battery_Ultra'], result: { id: 'acid_battery_mega', name: 'Acid Battery Mega', emoji: '☣️', tier: 13 } },
  { ingredients: ['AI_Battery', 'Acid_Rain'], result: { id: 'acid_rain_battery', name: 'Acid Rain Battery', emoji: '☣️', tier: 10 } },
  { ingredients: ['AI_Battery', 'Acid_Rain_Battery'], result: { id: 'acid_rain_battery_plus', name: 'Acid Rain Battery Plus', emoji: '☣️', tier: 11 } },
  { ingredients: ['AI_Battery', 'Acid_Rain_Battery_Plus'], result: { id: 'acid_rain_battery_ultra', name: 'Acid Rain Battery Ultra', emoji: '☣️', tier: 12 } },
  { ingredients: ['AI_Battery', 'Acid_Rain_Battery_Ultra'], result: { id: 'acid_rain_battery_mega', name: 'Acid Rain Battery Mega', emoji: '☣️', tier: 13 } },
  { ingredients: ['AI_Battery', 'Acid_Sludge'], result: { id: 'acid_sludge_battery', name: 'Acid Sludge Battery', emoji: '☣️', tier: 11 } },
  { ingredients: ['AI_Battery', 'Acid_Sludge_Battery'], result: { id: 'acid_sludge_battery_plus', name: 'Acid Sludge Battery Plus', emoji: '☣️', tier: 12 } },
  { ingredients: ['AI_Battery', 'Acid_Sludge_Battery_Plus'], result: { id: 'acid_sludge_battery_ultra', name: 'Acid Sludge Battery Ultra', emoji: '☣️', tier: 13 } },
  { ingredients: ['AI_Battery', 'AI_Battery'], result: { id: 'super_ai_battery', name: 'Super AI Battery', emoji: '🔋', tier: 15 } },
  { ingredients: ['AI_Battery', 'AI_Cloud'], result: { id: 'ai_cloud_battery', name: 'AI Cloud Battery', emoji: '☁️', tier: 14 } },
  { ingredients: ['AI_Battery', 'AI_Cloud_Battery'], result: { id: 'ai_cloud_battery_plus', name: 'AI Cloud Battery Plus', emoji: '☁️', tier: 15 } },
  { ingredients: ['AI_Battery', 'AI_Cloud_Battery_Plus'], result: { id: 'ai_cloud_battery_ultra', name: 'AI Cloud Battery Ultra', emoji: '☁️', tier: 16 } },
  { ingredients: ['AI_Battery', 'AI_Cloud_Battery_Ultra'], result: { id: 'ai_cloud_battery_mega', name: 'AI Cloud Battery Mega', emoji: '☁️', tier: 17 } },
  { ingredients: ['AI_Battery', 'AI_Battery'], result: { id: 'super_ai_battery', name: 'Super AI Battery', emoji: '🔋', tier: 15 } },
  { ingredients: ['AI_Battery', 'AI_Cloud'], result: { id: 'ai_cloud_battery', name: 'AI Cloud Battery', emoji: '☁️', tier: 14 } },
  { ingredients: ['AI_Battery', 'AI_Cloud_Battery'], result: { id: 'ai_cloud_battery_plus', name: 'AI Cloud Battery Plus', emoji: '☁️', tier: 15 } },
  { ingredients: ['AI_Battery', 'AI_Cloud_Battery_Plus'], result: { id: 'ai_cloud_battery_ultra', name: 'AI Cloud Battery Ultra', emoji: '☁️', tier: 16 } },
  { ingredients: ['AI_Battery', 'Acid_Ash'], result: { id: 'acid_ash_battery', name: 'Acid Ash Battery', emoji: '☣️', tier: 10 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Battery'], result: { id: 'acid_ash_battery_plus', name: 'Acid Ash Battery Plus', emoji: '☣️', tier: 11 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Battery_Plus'], result: { id: 'acid_ash_battery_ultra', name: 'Acid Ash Battery Ultra', emoji: '☣️', tier: 12 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Battery_Ultra'], result: { id: 'acid_ash_battery_mega', name: 'Acid Ash Battery Mega', emoji: '☣️', tier: 13 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile'], result: { id: 'acid_ash_pile_battery', name: 'Acid Ash Pile Battery', emoji: '☣️', tier: 11 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile_Battery'], result: { id: 'acid_ash_pile_battery_plus', name: 'Acid Ash Pile Battery Plus', emoji: '☣️', tier: 12 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile_Battery_Mega'], result: { id: 'acid_ash_pile_battery_ultra', name: 'Ash Pile Battery Ultra', emoji: '☣️', tier: 14 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile_Battery_Plus'], result: { id: 'acid_ash_pile_battery_ultra', name: 'Ash Pile Battery Ultra', emoji: '☣️', tier: 13 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile_Battery_Ultra'], result: { id: 'acid_ash_pile_battery_mega', name: 'Ash Pile Battery Mega', emoji: '☣️', tier: 14 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile_Plus'], result: { id: 'acid_ash_pile_plus_battery', name: 'Ash Pile Plus Battery', emoji: '☣️', tier: 12 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile_Plus_Battery'], result: { id: 'acid_ash_pile_plus_battery_plus', name: 'Ash Pile Plus Battery', emoji: '☣️', tier: 13 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile_Rain'], result: { id: 'acid_ash_pile_rain_battery', name: 'Acid Ash Pile Rain Battery', emoji: '☣️', tier: 12 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile_Rain_Battery'], result: { id: 'acid_ash_pile_rain_battery_plus', name: 'Acid Ash Pile Rain Battery Plus', emoji: '☣️', tier: 13 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile_Rain_Battery_Plus'], result: { id: 'acid_ash_pile_rain_battery_ultra', name: 'Acid Ash Pile Rain Battery Ultra', emoji: '☣️', tier: 14 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile_Rain_Battery_Ultra'], result: { id: 'acid_ash_pile_rain_battery_mega', name: 'Ash Pile Rain Mega', emoji: '☣️', tier: 15 } },
  { ingredients: ['AI_Battery', 'Acid_Battery'], result: { id: 'acid_battery_plus', name: 'Acid Battery Plus', emoji: '☣️', tier: 11 } },
  { ingredients: ['AI_Battery', 'Acid_Battery_Mega'], result: { id: 'acid_battery_ultra', name: 'Acid Battery Ultra', emoji: '☣️', tier: 13 } },
  { ingredients: ['AI_Battery', 'Acid_Battery_Plus'], result: { id: 'acid_battery_ultra', name: 'Acid Battery Ultra', emoji: '☣️', tier: 12 } },
  { ingredients: ['AI_Battery', 'Acid_Battery_Ultra'], result: { id: 'acid_battery_mega', name: 'Acid Battery Mega', emoji: '☣️', tier: 13 } },
  { ingredients: ['AI_Battery', 'Acid_Rain'], result: { id: 'acid_rain_battery', name: 'Acid Rain Battery', emoji: '☣️', tier: 10 } },
  { ingredients: ['AI_Battery', 'Acid_Rain_Battery'], result: { id: 'acid_rain_battery_plus', name: 'Acid Rain Battery Plus', emoji: '☣️', tier: 11 } },
  { ingredients: ['AI_Battery', 'Acid_Rain_Battery_Mega'], result: { id: 'acid_rain_battery_ultra', name: 'Acid Rain Battery Ultra', emoji: '☣️', tier: 13 } },
  { ingredients: ['AI_Battery', 'Acid_Rain_Battery_Plus'], result: { id: 'acid_rain_battery_ultra', name: 'Acid Rain Battery Ultra', emoji: '☣️', tier: 12 } },
  { ingredients: ['AI_Battery', 'Acid_Rain_Battery_Ultra'], result: { id: 'acid_rain_battery_mega', name: 'Acid Rain Battery Mega', emoji: '☣️', tier: 13 } },
  { ingredients: ['AI_Battery', 'Acid_Sludge'], result: { id: 'acid_sludge_battery', name: 'Acid Sludge Battery', emoji: '☣️', tier: 11 } },
  { ingredients: ['AI_Battery', 'Acid_Sludge_Battery'], result: { id: 'acid_sludge_battery_plus', name: 'Acid Sludge Battery Plus', emoji: '☣️', tier: 12 } },
  { ingredients: ['AI_Battery', 'Acid_Sludge_Battery_Plus'], result: { id: 'acid_sludge_battery_ultra', name: 'Acid Sludge Battery Ultra', emoji: '☣️', tier: 13 } },
  { ingredients: ['AI_Battery', 'Acid_Sludge_Battery_Ultra'], result: { id: 'acid_sludge_battery_mega', name: 'Acid Sludge Battery Mega', emoji: '☣️', tier: 14 } },
  { ingredients: ['AI_Battery', 'Acid_Ash'], result: { id: 'acid_ash_battery', name: 'Acid Ash Battery', emoji: '☣️', tier: 10 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Battery'], result: { id: 'acid_ash_battery_plus', name: 'Acid Ash Battery Plus', emoji: '☣️', tier: 11 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Battery_Plus'], result: { id: 'acid_ash_battery_ultra', name: 'Acid Ash Battery Ultra', emoji: '☣️', tier: 12 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile'], result: { id: 'acid_ash_pile_battery', name: 'Acid Ash Pile Battery', emoji: '☣️', tier: 11 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile_Battery'], result: { id: 'acid_ash_pile_battery_plus', name: 'Acid Ash Pile Battery Plus', emoji: '☣️', tier: 12 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile_Battery_Plus'], result: { id: 'acid_ash_pile_battery_ultra', name: 'Acid Ash Pile Battery Ultra', emoji: '☣️', tier: 13 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile_Battery_Ultra'], result: { id: 'acid_ash_pile_battery_mega', name: 'Acid Ash Pile Battery Mega', emoji: '☣️', tier: 14 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile_Plus'], result: { id: 'acid_ash_pile_plus_battery', name: 'Acid Ash Pile Plus Battery', emoji: '☣️', tier: 12 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile_Rain'], result: { id: 'acid_ash_pile_rain_battery', name: 'Acid Ash Pile Rain Battery', emoji: '☣️', tier: 12 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile_Rain_Battery'], result: { id: 'acid_ash_pile_rain_battery_plus', name: 'Acid Ash Pile Rain Battery Plus', emoji: '☣️', tier: 13 } },
  { ingredients: ['AI_Battery', 'Acid_Ash_Pile_Rain_Battery_Plus'], result: { id: 'acid_ash_pile_rain_battery_ultra', name: 'Acid Ash Pile Rain Battery Ultra', emoji: '☣️', tier: 14 } },
  { ingredients: ['AI_Battery', 'Acid_Battery'], result: { id: 'acid_battery_plus', name: 'Acid Battery Plus', emoji: '☣️', tier: 11 } },
  { ingredients: ['AI_Battery', 'Acid_Battery_Plus'], result: { id: 'acid_battery_ultra', name: 'Acid Battery Ultra', emoji: '☣️', tier: 12 } },
];


