import { Recipe } from '../types';

export const recipes: Recipe[] = [
  // Additional Recipes
  { ingredients: ['Acid_Ash', 'Acid_Ash'], result: { id: 'acid_ash_pile', name: 'Acid Ash Pile', emoji: '🌋', tier: 6 } },
  { ingredients: ['Acid_Ash', 'Acid_Battery'], result: { id: 'toxic_battery_ash', name: 'Toxic Battery Ash', emoji: '☣️', tier: 10 } },
  { ingredients: ['Acid_Ash', 'Acid_Rain'], result: { id: 'acid_sludge', name: 'Acid Sludge', emoji: '☣️', tier: 6 } },
  { ingredients: ['Acid_Ash', 'Acid_Rain'], result: { id: 'acid_sludge', name: 'Acid Sludge', emoji: '☣️', tier: 6 } },
  { ingredients: ['Acid_Ash', 'Acidic_CO2'], result: { id: 'toxic_co2_ash', name: 'Toxic CO2 Ash', emoji: '💨', tier: 7 } },
  { ingredients: ['Acid_Ash', 'Air'], result: { id: 'airborne_ash', name: 'Airborne Ash', emoji: '🌬️', tier: 5 } },
  { ingredients: ['Acid_Ash', 'Air_Battery'], result: { id: 'electric_ash', name: 'Electric Ash', emoji: '⚡', tier: 7 } },
  { ingredients: ['Acid_Ash', 'Airboat'], result: { id: 'ashy_airboat', name: 'Ashy Airboat', emoji: '🛶', tier: 12 } },
  { ingredients: ['Acid_Ash', 'Android'], result: { id: 'ashy_android', name: 'Ashy Android', emoji: '🤖', tier: 15 } },
  { ingredients: ['Acid_Ash', 'Angel'], result: { id: 'fallen_ash_angel', name: 'Fallen Ash Angel', emoji: '🖤', tier: 11 } },
  { ingredients: ['Rain', 'Rain'], result: { id: 'storm', name: 'Storm', emoji: '⛈️', tier: 4 } },
  { ingredients: ['Rain', 'Mountain'], result: { id: 'waterfall', name: 'Waterfall', emoji: '🌊', tier: 5 } },
  { ingredients: ['Rain', 'Tree'], result: { id: 'growth', name: 'Growth', emoji: '🌱', tier: 3 } },
  { ingredients: ['Rain', 'Sea'], result: { id: 'flood', name: 'Flood', emoji: '🌊', tier: 5 } },
  { ingredients: ['Rain', 'Machine'], result: { id: 'rust', name: 'Rust', emoji: '⚙️', tier: 4 } },
  { ingredients: ['Rain', 'Village'], result: { id: 'muddy_village', name: 'Muddy Village', emoji: '🏘️', tier: 5 } },
  { ingredients: ['Rain', 'Night'], result: { id: 'gloomy_night', name: 'Gloomy Night', emoji: '🌑', tier: 4 } },
  { ingredients: ['Rain', 'Sword'], result: { id: 'rusty_sword', name: 'Rusty Sword', emoji: '⚔️', tier: 4 } },
  { ingredients: ['Rain', 'Ocean'], result: { id: 'tsunami', name: 'Tsunami', emoji: '🌊', tier: 6 } },
  { ingredients: ['Rain', 'Charcoal'], result: { id: 'wet_charcoal', name: 'Wet Charcoal', emoji: '🪨', tier: 3 } },
  { ingredients: ['Acid_Ash', 'Animal'], result: { id: 'ashy_animal', name: 'Ashy Animal', emoji: '🐾', tier: 10 } },
  { ingredients: ['Acid_Ash', 'Aroma'], result: { id: 'burnt_aroma', name: 'Burnt Aroma', emoji: '👃', tier: 7 } },
  { ingredients: ['Acid_Ash', 'Artificial_Intelligence'], result: { id: 'ashy_ai', name: 'Ashy AI', emoji: '🧠', tier: 14 } },
  { ingredients: ['Acid_Ash', 'Artificial_Intelligence'], result: { id: 'ashy_ai', name: 'Ashy AI', emoji: '🧠', tier: 14 } },
  { ingredients: ['Acid_Ash', 'Ash'], result: { id: 'ash_pile', name: 'Ash Pile', emoji: '🌋', tier: 5 } },
  { ingredients: ['Acid_Ash', 'Atmosphere'], result: { id: 'ashy_atmosphere', name: 'Ashy Atmosphere', emoji: '🌍', tier: 8 } },
  { ingredients: ['Acid_Ash', 'Battery'], result: { id: 'ashy_battery', name: 'Ashy Battery', emoji: '🔋', tier: 7 } },
  { ingredients: ['Acid_Ash', 'Beach'], result: { id: 'ashy_beach', name: 'Ashy Beach', emoji: '🏖️', tier: 6 } },
  { ingredients: ['Acid_Ash', 'Big_Bang'], result: { id: 'cosmic_ash', name: 'Cosmic Ash', emoji: '🌌', tier: 16 } },
  { ingredients: ['Acid_Ash', 'Big_Bang'], result: { id: 'cosmic_ash', name: 'Cosmic Ash', emoji: '🌌', tier: 16 } },
  { ingredients: ['Acid_Ash', 'Bird'], result: { id: 'ashy_bird', name: 'Ashy Bird', emoji: '🐦', tier: 10 } },
  { ingredients: ['Acid_Ash', 'Boat'], result: { id: 'ashy_boat', name: 'Ashy Boat', emoji: '🛶', tier: 11 } },
  { ingredients: ['Acid_Ash', 'Breeze'], result: { id: 'ashy_breeze', name: 'Ashy Breeze', emoji: '🍃', tier: 6 } },
  { ingredients: ['Acid_Ash', 'Brick'], result: { id: 'ashy_brick', name: 'Ashy Brick', emoji: '🧱', tier: 6 } },
  { ingredients: ['Acid_Ash', 'Brilliant'], result: { id: 'glowing_ash', name: 'Glowing Ash', emoji: '✨', tier: 8 } },
  { ingredients: ['Acid_Ash', 'Carbon_Dioxide'], result: { id: 'co2_ash', name: 'CO2 Ash', emoji: '💨', tier: 6 } },
  { ingredients: ['Acid_Ash', 'Carbon_Dioxide'], result: { id: 'co2_ash', name: 'CO2 Ash', emoji: '💨', tier: 6 } },
  { ingredients: ['Acid_Ash', 'Cave'], result: { id: 'ashy_cave', name: 'Ashy Cave', emoji: '🕳️', tier: 6 } },
  { ingredients: ['Acid_Ash', 'Centaur'], result: { id: 'ashy_centaur', name: 'Ashy Centaur', emoji: '🏹', tier: 12 } },
];
