import { Recipe } from './types';

// Discover all recipe files dynamically using Vite's glob import
const modules = import.meta.glob('/src/recipes/*.ts', { eager: true });

/**
 * Aggregates all recipes from all files in /src/recipes/
 */
export const getAllRecipes = (): Recipe[] => {
  const allRecipes: Recipe[] = [];
  for (const path in modules) {
    const mod = modules[path] as { recipes: Recipe[] };
    if (mod && mod.recipes) {
      allRecipes.push(...mod.recipes);
    }
  }
  return allRecipes;
};

/**
 * Returns statistics and warnings about the current recipe set
 */
export const getStatusInfo = () => {
  const recipes = getAllRecipes();
  const count = recipes.length;
  
  // RAM Estimation: Roughly 0.5KB per recipe object in memory (including indexing)
  const ramMB = (count * 0.5) / 1024;
  
  let warning = "";
  let statusColor = "text-emerald-500";

  if (count > 5000) {
    warning = "⚠️ Large dataset. Performance monitoring recommended.";
    statusColor = "text-amber-500";
  }
  if (count > 20000) {
    warning = "🛑 Critical scale. Mobile devices may experience lag.";
    statusColor = "text-rose-500";
  }
  
  return { count, ramMB, warning, statusColor, recipes };
};

/**
 * Opens a new tab with a detailed manifest of all recipes
 */
export const openRecipeViewer = () => {
  const { count, recipes, ramMB, warning } = getStatusInfo();
  const win = window.open("", "_blank");
  if (win) {
    const recipeList = recipes.map(r => `
      <div style="padding: 12px; border-bottom: 1px solid #222; display: flex; justify-content: space-between; align-items: center;">
        <div style="display: flex; gap: 10px; align-items: center;">
          <span style="opacity: 0.5; font-size: 12px;">[${r.ingredients[0]}] + [${r.ingredients[1]}]</span>
          <span style="font-size: 18px;">→</span>
          <span style="font-size: 16px; font-weight: bold;">${r.result.emoji} ${r.result.name}</span>
        </div>
        <span style="font-size: 10px; background: #333; padding: 2px 6px; border-radius: 4px;">TIER ${r.result.tier}</span>
      </div>
    `).join("");

    win.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Alchemy Manifest (${count} Recipes)</title>
          <style>
            body { 
              background: #050505; 
              color: #a1a1aa; 
              font-family: 'Inter', -apple-system, sans-serif; 
              padding: 60px; 
              max-width: 900px; 
              margin: 0 auto;
              line-height: 1.6; 
            }
            .header { 
              border-bottom: 1px solid #222; 
              padding-bottom: 30px; 
              margin-bottom: 40px; 
            }
            h1 { color: #fff; letter-spacing: -0.02em; margin-bottom: 8px; }
            .warning { 
              color: #fca5a5; 
              background: #450a0a; 
              padding: 16px; 
              border-radius: 8px; 
              margin: 20px 0; 
              font-size: 14px;
              border: 1px solid #7f1d1d;
            }
            .stat-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 20px; margin-bottom: 20px; }
            .stat-card { background: #111; padding: 20px; border-radius: 12px; border: 1px solid #222; }
            .stat-label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.1em; opacity: 0.5; margin-bottom: 4px; }
            .stat-value { font-size: 24px; color: #fff; font-weight: 600; }
            .list { background: #0a0a0a; border: 1px solid #222; border-radius: 12px; overflow: hidden; }
            b { color: #fff; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Alchemy Manifest</h1>
            <p>A complete technical audit of all combinations currently indexed in the application.</p>
          </div>
          
          <div class="stat-grid">
            <div class="stat-card">
              <div class="stat-label">Total Combinations</div>
              <div class="stat-value">${count.toLocaleString()}</div>
            </div>
            <div class="stat-card">
              <div class="stat-label">Est. RAM Overhead</div>
              <div class="stat-value">${ramMB.toFixed(2)} MB</div>
            </div>
          </div>

          ${warning ? `<div class="warning">${warning}</div>` : ""}
          
          <div class="list">
            ${recipeList}
          </div>
          
          <footer style="margin-top: 60px; font-size: 11px; opacity: 0.3; text-align: center; text-transform: uppercase; letter-spacing: 0.2em;">
            Generated by Alchemy Status Engine
          </footer>
        </body>
      </html>
    `);
    win.document.close();
  }
};
